### ISSUE TITLE
Register of organization units

### ISSUE THREAD

**Issue by chenejac** [sci2zero/TeslaRIS-backend#17]
**Tasks**
- [x] Browse (hierarchy - tree) and search of organization units
- [x] https://github.com/chenejac/TeslaRIS-backend/issues/16
- [ ] Drag and drop of organization units
