### ISSUE TITLE
Register of researchers

### ISSUE THREAD

**Issue by chenejac** [sci2zero/TeslaRIS-backend#18]
**Tasks**
- [x] Browse by affiliated organization units and search of researchers
    - [x] Search and filtering of researchers
    - [x] Pagination of list of researchers
    - [x] See details
- [x] https://github.com/chenejac/TeslaRIS-backend/issues/16
- [x] https://github.com/chenejac/TeslaRIS-backend/issues/10
- [x] https://github.com/chenejac/TeslaRIS-backend/issues/12
