### ISSUE TITLE
Registry of assessment rulebooks 

### ISSUE THREAD

**Issue by chenejac** [sci2zero/TeslaRIS-backend#97]
**Tasks**
- [ ] Endpoint for CRUD operations over the following entities: AssessmentRulebook, AssessmentMeasure, AssessmentClassification
- [ ] UI for registry of AssessmentRulebook, AssessmentMeasure, AssessmentClassification
- [ ] DSL for formalDescriptionOfRule for AssessmentMeasure and AssessmentClassification (engine for execution and UI for definition of rules)
